### ISSUE TITLE
calculateIntercept will only return Down Side or North Side

### ISSUE THREAD

**Issue by UnknownOre** [pmmp/Math#52]
so i was testing the faces from Ray Trace result returns using a pearl no matter from where i throw the pearl the faces will always return  Down Side (0) or North Side (2), is it supposed to be like that or that just a bug todo with calculateIntercept in boundingBoxes?

**Comment by dktapps** [comment]
It's just you. If this was actually broken, all kinds of things would be broken with it, such as arrows.
