### ISSUE TITLE
Fatal error in Matrix class with PHP 8.1

### ISSUE THREAD

**Issue by Nerahikada** [pmmp/Math#76]
```
Fatal error: During inheritance of ArrayAccess: Uncaught ErrorException: Return type of pocketmine\math\Matrix::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/pmmp/crash/PocketMine-MP.phar/vendor/pocketmine/math/src/Matrix.php:43
```

PocketMine-MP version: 4.7.3 [Protocol 544]
Git commit: pmmp/PocketMine-MP@b5a049d1fe40cb1be44d7876564994e87cb76bd1
PHP version: 8.1.9
OS: Linux, linux

Composer libraries:
- pocketmine/math 0.4.2@ aacc3759a508a69dfa5bc4dfa770ab733c5c94bf

**Comment by dktapps** [comment]
If you want, you could submit a PR to add the ReturnTypeWillChange attribute.
